spring.application.name=Automation-tool
#spring.mail.host=smtp.gmail.com
spring.mail.host=${SPRING_MAIL_HOST}
#spring.mail.port=587
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
#spring.mail.username=prasannmalanaik@gmail.com
#spring.mail.password=bfxs iqrg merg jaxu
#spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
#spring.port=8080
#multipart file configurations
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

